import {
  BrowserWindow
} from 'electron';

// This allows TypeScript to pick up the magic constant that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

export interface NewWindowOption {
  width?: number,
  height?: number,
  url?: string,
}

export const createWindow = (args: NewWindowOption = {}): BrowserWindow => {
  const win = new BrowserWindow({
    width: args.width || 1024,
    height: args.height || 720,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      worldSafeExecuteJavaScript: true,
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  win.loadURL(args.url || MAIN_WINDOW_WEBPACK_ENTRY);
  // Open the DevTools.
  win.webContents.openDevTools();
  return win;
}
